<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <AssemblyName>Approximately21</AssemblyName>
        <Product>Approximately21</Product>
        <Version>1.0.0</Version>
        <ApproximatelyUpDirectory>C:\Program Files (x86)\Steam\steamapps\common\Approximately Up</ApproximatelyUpDirectory>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>latest</LangVersion>
        <RestoreAdditionalProjectSources>
            https://api.nuget.org/v3/index.json;
            https://nuget.bepinex.dev/v3/index.json;
            https://nuget.samboy.dev/v3/index.json
        </RestoreAdditionalProjectSources>
        <RootNamespace>Approximately21</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.*" IncludeAssets="compile"/>
        <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Assembly-CSharp">
            <HintPath>$(ApproximatelyUpDirectory)\BepInEx\interop\Assembly-CSharp.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Il2Cppmscorlib">
            <HintPath>$(ApproximatelyUpDirectory)\BepInEx\interop\Il2Cppmscorlib.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Il2CppSystem">
            <HintPath>$(ApproximatelyUpDirectory)\BepInEx\interop\Il2CppSystem.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Unity.Entities">
          <HintPath>..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Approximately Up\BepInEx\interop\Unity.Entities.dll</HintPath>
        </Reference>
        <Reference Include="Unity.Collections">
            <HintPath>$(ApproximatelyUpDirectory)\BepInEx\interop\Unity.Collections.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Unity.Mathematics">
            <HintPath>$(ApproximatelyUpDirectory)\BepInEx\interop\Unity.Mathematics.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Unity.Transforms">
            <HintPath>$(ApproximatelyUpDirectory)\BepInEx\interop\Unity.Transforms.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>$(ApproximatelyUpDirectory)\BepInEx\interop\UnityEngine.CoreModule.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Unity.InputSystem">
            <HintPath>$(ApproximatelyUpDirectory)\BepInEx\interop\Unity.InputSystem.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.UI">
            <HintPath>$(ApproximatelyUpDirectory)\BepInEx\interop\UnityEngine.UI.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.AssetBundleModule">
            <HintPath>$(ApproximatelyUpDirectory)\BepInEx\interop\UnityEngine.AssetBundleModule.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="..\lib\BlackjackTableBundle\Built\BlackjackTableMesh.bin">
        <LogicalName>Approximately21.BlackjackTableMesh.bin</LogicalName>
        <Link>Assets\BlackjackTableMesh.bin</Link>
      </EmbeddedResource>
    </ItemGroup>
</Project>
